import type { SentimentLabel } from "./mlModels.js";

export interface SampleEntry {
  id: number;
  text: string;
  label: SentimentLabel;
  source: string;
}

export const SAMPLE_DATASET: SampleEntry[] = [
  { id: 1, text: "I love this product! It's absolutely amazing and works perfectly.", label: "positive", source: "Twitter" },
  { id: 2, text: "This is the worst experience I've ever had. Completely terrible.", label: "negative", source: "Twitter" },
  { id: 3, text: "The weather today is cloudy. It might rain later.", label: "neutral", source: "Twitter" },
  { id: 4, text: "Just had the best coffee of my life! So happy right now!", label: "positive", source: "Twitter" },
  { id: 5, text: "Disgusting service. Never coming back again. Waste of money.", label: "negative", source: "Twitter" },
  { id: 6, text: "The meeting is scheduled for 3 PM tomorrow in room 204.", label: "neutral", source: "Twitter" },
  { id: 7, text: "Outstanding performance! The team exceeded all expectations.", label: "positive", source: "Twitter" },
  { id: 8, text: "Horrible customer support. They ignored my complaint for weeks.", label: "negative", source: "Twitter" },
  { id: 9, text: "The new software update has been released. Users can download it now.", label: "neutral", source: "Twitter" },
  { id: 10, text: "This movie was so touching! I cried tears of joy. Pure masterpiece.", label: "positive", source: "Twitter" },
  { id: 11, text: "I am so frustrated with this broken app. Nothing works correctly.", label: "negative", source: "Twitter" },
  { id: 12, text: "The quarterly report shows a 5% increase in revenue compared to last year.", label: "neutral", source: "Twitter" },
  { id: 13, text: "Absolutely thrilled with my new phone! Best purchase decision ever.", label: "positive", source: "Twitter" },
  { id: 14, text: "What a disappointment. Expected so much more from this brand.", label: "negative", source: "Twitter" },
  { id: 15, text: "Scientists have discovered a new species of fish in the Pacific Ocean.", label: "neutral", source: "Twitter" },
  { id: 16, text: "The concert was phenomenal! The crowd was electric and the music was perfect.", label: "positive", source: "Twitter" },
  { id: 17, text: "This food is absolutely disgusting. How can anyone eat this?", label: "negative", source: "Twitter" },
  { id: 18, text: "The library will be closed on Monday for maintenance.", label: "neutral", source: "Twitter" },
  { id: 19, text: "So grateful for all the support and love from my friends and family!", label: "positive", source: "Twitter" },
  { id: 20, text: "Terrible traffic today. Stuck in a jam for two hours with no end in sight.", label: "negative", source: "Twitter" },
  { id: 21, text: "The price of oil has increased by 3% this week due to supply constraints.", label: "neutral", source: "Twitter" },
  { id: 22, text: "Just got promoted at work! Hard work really does pay off. So excited!", label: "positive", source: "Twitter" },
  { id: 23, text: "The service was extremely rude and unprofessional. Unacceptable behavior.", label: "negative", source: "Twitter" },
  { id: 24, text: "The train arrives at platform 7 at 6:30 AM every morning.", label: "neutral", source: "Twitter" },
  { id: 25, text: "What a beautiful sunny day! Feeling so alive and full of energy.", label: "positive", source: "Twitter" },
  { id: 26, text: "Cannot believe how bad this product is. Total waste of my money.", label: "negative", source: "Twitter" },
  { id: 27, text: "The government has announced new infrastructure development plans.", label: "neutral", source: "Twitter" },
  { id: 28, text: "My team won the championship! Dreams really do come true!", label: "positive", source: "Twitter" },
  { id: 29, text: "Lost my wallet today. This day cannot get any worse.", label: "negative", source: "Twitter" },
  { id: 30, text: "The documentary explores the history of ancient civilizations.", label: "neutral", source: "Twitter" },
  { id: 31, text: "Incredible experience at the museum! Learning so much about history.", label: "positive", source: "Twitter" },
  { id: 32, text: "Stuck in bed with a terrible cold. Feeling absolutely miserable.", label: "negative", source: "Twitter" },
  { id: 33, text: "The bank operates from 9 AM to 5 PM on weekdays.", label: "neutral", source: "Twitter" },
  { id: 34, text: "This book changed my perspective on life! Highly recommend to everyone.", label: "positive", source: "Twitter" },
  { id: 35, text: "The landlord refuses to fix anything. Living conditions are awful.", label: "negative", source: "Twitter" },
  { id: 36, text: "The university will begin accepting applications for the fall semester.", label: "neutral", source: "Twitter" },
  { id: 37, text: "Fantastic birthday surprise! My friends are truly the best people.", label: "positive", source: "Twitter" },
  { id: 38, text: "This is completely broken and useless. I demand a full refund immediately.", label: "negative", source: "Twitter" },
  { id: 39, text: "Construction work will continue on Main Street for the next two weeks.", label: "neutral", source: "Twitter" },
  { id: 40, text: "Fell in love with this restaurant! The food was extraordinary.", label: "positive", source: "Twitter" },
  { id: 41, text: "My flight was cancelled and no one bothered to notify me. Furious!", label: "negative", source: "Twitter" },
  { id: 42, text: "The new policy will come into effect starting January 1st.", label: "neutral", source: "Twitter" },
  { id: 43, text: "Proud of my daughter's graduation! She worked so hard for this.", label: "positive", source: "Twitter" },
  { id: 44, text: "The app keeps crashing every five minutes. Extremely unreliable software.", label: "negative", source: "Twitter" },
  { id: 45, text: "Researchers have published a new study on climate change in Nature.", label: "neutral", source: "Twitter" },
  { id: 46, text: "Best vacation ever! The beaches were stunning and the food was divine.", label: "positive", source: "Twitter" },
  { id: 47, text: "Waited 45 minutes for my order and it arrived cold and wrong. Unacceptable.", label: "negative", source: "Twitter" },
  { id: 48, text: "The annual conference will be held in Chicago this November.", label: "neutral", source: "Twitter" },
  { id: 49, text: "Finally finished my thesis! Years of hard work now paying off!", label: "positive", source: "Twitter" },
  { id: 50, text: "The internet has been down for 8 hours. This is completely unacceptable.", label: "negative", source: "Twitter" },
  { id: 51, text: "The committee will review the proposal during next week's session.", label: "neutral", source: "Twitter" },
  { id: 52, text: "Such an inspiring speech! Really motivated me to chase my dreams.", label: "positive", source: "Twitter" },
  { id: 53, text: "Ripped off by this company. Never trust their advertising.", label: "negative", source: "Twitter" },
  { id: 54, text: "The store opens at 10 AM and closes at 9 PM daily.", label: "neutral", source: "Twitter" },
  { id: 55, text: "Amazing customer service! They went above and beyond to help me.", label: "positive", source: "Twitter" },
  { id: 56, text: "I hate this city. Noisy, dirty, and the people are unfriendly.", label: "negative", source: "Twitter" },
  { id: 57, text: "The temperature today is expected to reach 25 degrees Celsius.", label: "neutral", source: "Twitter" },
  { id: 58, text: "This workout routine is absolutely transforming my body and mindset!", label: "positive", source: "Twitter" },
  { id: 59, text: "Embarrassingly poor quality for the price they charge. Disgusting.", label: "negative", source: "Twitter" },
  { id: 60, text: "The elections will be held on the first Tuesday of next month.", label: "neutral", source: "Twitter" },
  { id: 61, text: "Thrilled to announce that I got accepted to my dream university!", label: "positive", source: "Twitter" },
  { id: 62, text: "Zero stars if I could. The worst hotel I have ever stayed in my life.", label: "negative", source: "Twitter" },
  { id: 63, text: "The survey results will be published in the upcoming quarterly report.", label: "neutral", source: "Twitter" },
  { id: 64, text: "This is absolutely the best decision I have ever made in my life!", label: "positive", source: "Twitter" },
  { id: 65, text: "Misleading description. Product looks nothing like the photos.", label: "negative", source: "Twitter" },
  { id: 66, text: "The company will release its financial results on Thursday.", label: "neutral", source: "Twitter" },
  { id: 67, text: "So thankful for the kind strangers who helped me when I was lost!", label: "positive", source: "Twitter" },
  { id: 68, text: "Absolutely exhausted and drained from this toxic work environment.", label: "negative", source: "Twitter" },
  { id: 69, text: "The spacecraft successfully reached its designated orbit this morning.", label: "neutral", source: "Twitter" },
  { id: 70, text: "The sunrise this morning was breathtaking! Nature is so beautiful.", label: "positive", source: "Twitter" },
  { id: 71, text: "Completely let down by this service. They promised and failed to deliver.", label: "negative", source: "Twitter" },
  { id: 72, text: "The department will undergo a restructuring process in the coming months.", label: "neutral", source: "Twitter" },
  { id: 73, text: "Overjoyed to announce my engagement! She said yes! Best day of my life!", label: "positive", source: "Twitter" },
  { id: 74, text: "This is daylight robbery. Paid triple the market price for nothing.", label: "negative", source: "Twitter" },
  { id: 75, text: "The museum will display the artifact collection from Tuesday to Sunday.", label: "neutral", source: "Twitter" },
  { id: 76, text: "Won first place at the science fair! All the hard work paid off!", label: "positive", source: "Twitter" },
  { id: 77, text: "The system is completely broken. Nothing has worked since the update.", label: "negative", source: "Twitter" },
  { id: 78, text: "The new bridge connecting the two districts will open next spring.", label: "neutral", source: "Twitter" },
  { id: 79, text: "Crying happy tears! My novel just got published after 5 years of work!", label: "positive", source: "Twitter" },
  { id: 80, text: "Worst experience of my entire life. I want to forget this ever happened.", label: "negative", source: "Twitter" },
  { id: 81, text: "The council will vote on the proposed budget amendments on Friday.", label: "neutral", source: "Twitter" },
  { id: 82, text: "I'm so blessed to have such wonderful people in my life!", label: "positive", source: "Twitter" },
  { id: 83, text: "This product literally broke on the first day of use. Complete garbage.", label: "negative", source: "Twitter" },
  { id: 84, text: "The athlete completed the race in 9.8 seconds setting a new record.", label: "neutral", source: "Twitter" },
  { id: 85, text: "Just finished reading the most amazing book! Cannot wait for the sequel.", label: "positive", source: "Twitter" },
  { id: 86, text: "Absolutely regretting this purchase. Money completely down the drain.", label: "negative", source: "Twitter" },
  { id: 87, text: "The parliament will reconvene after the holiday break on January 10th.", label: "neutral", source: "Twitter" },
  { id: 88, text: "My startup just closed its first funding round! Dreams becoming reality!", label: "positive", source: "Twitter" },
  { id: 89, text: "Deeply unhappy with this service. This has ruined my entire week.", label: "negative", source: "Twitter" },
  { id: 90, text: "The annual budget review meeting will take place on March 15th.", label: "neutral", source: "Twitter" },
  { id: 91, text: "So excited about this new opportunity! Cannot believe this is happening!", label: "positive", source: "Twitter" },
  { id: 92, text: "Disgusting attitude from staff. I will never return to this place.", label: "negative", source: "Twitter" },
  { id: 93, text: "The satellite data shows an increase in ocean temperatures this year.", label: "neutral", source: "Twitter" },
  { id: 94, text: "This app has completely changed how I manage my time! So efficient!", label: "positive", source: "Twitter" },
  { id: 95, text: "Infuriating. Three hours waiting on hold and still no solution given.", label: "negative", source: "Twitter" },
  { id: 96, text: "The foundation was established in 1985 to support local education.", label: "neutral", source: "Twitter" },
  { id: 97, text: "Married my best friend today. Happiest day of my entire life!", label: "positive", source: "Twitter" },
  { id: 98, text: "Scammed online. Lost all my savings. This company is fraudulent.", label: "negative", source: "Twitter" },
  { id: 99, text: "The highway will be under maintenance every Sunday night until April.", label: "neutral", source: "Twitter" },
  { id: 100, text: "Incredible journey! This experience has made me grow so much as a person.", label: "positive", source: "Twitter" },
];

export function getDefaultDataset(): { texts: string[]; labels: SentimentLabel[] } {
  return {
    texts: SAMPLE_DATASET.map(e => e.text),
    labels: SAMPLE_DATASET.map(e => e.label),
  };
}
